#!/bin/bash

#####################################################################
#  Script to build the Lexer, parser, visitor and listener with ANTLR
#  First argument is the ANTLR.jar file
#  Second argument is the input C program file
#  Third argument is the output P program file
#####################################################################

java -jar $1 -Dlanguage=Python3 SmallC.g4 -visitor
python3 c2p.py $2 $3
