#!/bin/bash

#####################################################################
#  Script to execute the generated p code in folder p_output
#  First argument is the Pmachine executable
#####################################################################
if [ $# -eq 0 ]
  then
    echo "You need to specify the Pmachine executable as the first argument"
    exit 1
fi

for file in "p_output/*.p"
do
  echo "Executing p code for file" $file
  $1 $file
done
